version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: ${{ secrets.NuGet_ApiKey_Appveyor }}
  skip_symbols: true
  artifact: /.*\.nupkg/